### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by BalassaMarton** [350d/70Mai_A800S_Firmware#5]
Hi, I'd really like to have custom firmware for my camera, but I'm hesitant on installing just a binary without source code. I'm also curious how it works, because I have some ideas I'd like to see in my camera software (like connecting to an existing network instead of creating a hotspot). Could you share the source code as well?

**Comment by 350d** [comment]
Hello!
For source code/manual development please check #1 Issue.
You can unpack and repack firmware file manually.
For connecting to existing wifi network - check my latest update. There is `autorun_sta.sh` where you can set ssid/pass and other networks settings. Dashcam will connect to your network. The problem is that in this mode your mobile app will not find this dashcam. I guess app trying to find dashcam on *.*.*.1 ip or something.

**Comment by BalassaMarton** [comment]
Wow, so this cam is actually running linux? Theoretically, would it be possible to completely rewrite its firmware and add new features?

**Comment by 350d** [comment]
Theoretically - yes.
